# Generated by Django 5.2.4 on 2025-07-13 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordering.product'),
        ),
    ]
