# Generated by Django 5.2.4 on 2025-07-15 03:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_alter_order_created_by_alter_product_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='User',
        ),
    ]
